services:
  ubuntu:
    image: ghcr.io/owenjones/scct-dev-environment:${SDC_RELEASE-latest}
    hostname: scctdev
    volumes:
      - '../:/home/scct:z'
      - './mariadb/socket:/var/run/mysqld:z'

  mysql:
    image: mariadb:latest
    volumes:
      - './mariadb/db:/var/lib/mysql:Z'
      - './mariadb/init:/docker-entrypoint-initdb.d'
      - './mariadb/socket:/var/run/mysqld:z'
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=${MARIADB_USER-scct}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD-scctdev}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD-password}
      - MARIADB_AUTO_UPGRADE=true

  mongodb:
    image: mongo:latest
    volumes:
      - './mongodb:/data/db:Z'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD-password}

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT-8080}:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=${MARIADB_USER-scct}
      - PMA_PASSWORD=${MARIADB_PASSWORD-scctdev}
      - PMA_PMADB=phpmyadmin
      - PMA_CONTROLUSER=phpmyadmin
      - PMA_CONTROLPASS=60cfd180192e88712c3d1d638bba67730ce5

  mongo-express:
    image: mongo-express:latest
    ports:
      - ${MONGOEXPRESS_PORT-8081}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD-password}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USER-root}:${MONGO_ROOT_PASSWORD-password}@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
