name: build_release
run-name: ${{ github.actor }} is building release ${{ github.event.release.name }}
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add release tag to devcontainer env
        working-directory: ./scct-dev-environment
        run: echo "SDC_RELEASE=\"${{ github.event.release.name }}\"" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:build"
          push: true
          tags: owenjones/scct-dev-environment:${{ github.event.release.name }}
        
      - name: Zip workspace
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          path: "scct-dev-environment"
          filename: "scct-dev-environment-${{ github.event.release.name }}.zip"
        
      - name: Attach zipped workspace to release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "scct-dev-environment-${{ github.event.release.name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}